name: Build kind cluster component images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      fail-fast: false
      matrix:
        component:
          - local-path-provisioner
          - local-path-helper
          - base
          - kindnetd
          - haproxy

    env:
      IMAGE_REGISTRY: quay.io
      REGISTRY: quay.io/powercloud
      PLATFORMS: linux/ppc64le

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log into registry ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Clone and patch kubernetes-sigs/kind repository
        run: |
          git clone --depth 1 --branch $(cat KIND_VERSION) https://github.com/kubernetes-sigs/kind.git
          cd kind
          git apply ../build-ppc64le.patch
          echo "TAG=$(date +v%Y%m%d)-$(git describe --always)" >> $GITHUB_ENV

      - name: Build kind-${{ matrix.component }}
        working-directory: ./kind
        run: |
          IMAGE_NAME=kind-${{ matrix.component }} make -C images/${{ matrix.component }} push
